Conf/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blogs/', include('blogs.urls', namespace="blogs")),
    path('', include('users.urls', namespace="users")),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

blogs/urls.py
from django.urls import path
from . import views

app_name = "blogs"

urlpatterns = [
    path('', views.home_page_view, name="home"),
    path('blogs/', views.blogs_page_view, name="list"),
    path('alkckjlbdvelrbrkbevbrltjerblbjr/', views.contact_page_view, name="contact"),
]

users/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path

from .views import register_view, login_view, email_confirm_view

app_name = 'users'

urlpatterns = [
    path('register/', register_view, name='register'),  # User registration
    path('login/', login_view, name='login'),  # User login
    path('logout/', LogoutView.as_view(), name='logout'),  # User logout
    path('confirm/<int:uid>/<str:token>/', email_confirm_view, name='email_confirm'),  # Email confirmation
]

blogs/models.py
from django.db import models


class AuthorsModel(models.Model):
    full_name = models.CharField(max_length=255)
    age = models.PositiveSmallIntegerField()
    is_active = models.BooleanField(default=True)
    email = models.EmailField(null=True, blank=True)

    def __repr__(self):
        return self.full_name

    def __str__(self):
        return self.full_name

    class Meta:
        verbose_name = "author"
        verbose_name_plural = "authors"


class CategoryModel(models.Model):
    title = models.CharField(max_length=255)

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __repr__(self):
        return self.title

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "category"
        verbose_name_plural = "categories"


class BlogsModel(models.Model):
    author = models.ForeignKey(AuthorsModel, on_delete=models.CASCADE)
    categories = models.ManyToManyField(CategoryModel)

    title = models.CharField(max_length=255, null=True, blank=True, default="default")
    content = models.TextField()
    image = models.ImageField(upload_to='blogs')

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __repr__(self):
        return self.title

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "blog"
        verbose_name_plural = "blogs"


"""
teachers
groups
students
homeworks
"""

najot/models.py
from django.db import models


class TestFormModel(models.Model):
    file = models.FileField(upload_to='test')

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


class CustomUserModel(AbstractUser):
    email = models.EmailField(unique=True)

najot/forms.py
from django import forms

from .models import TestFormModel


class TestForm(forms.ModelForm):
    class Meta:
        model = TestFormModel
        fields = '__all__'

users/forms.py
# forms.py
from django.contrib.auth.forms import UserCreationForm

from .models import CustomUserModel


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUserModel
        fields = ('username', 'email', 'password1', 'password2')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if CustomUserModel.objects.filter(email=email).exists():
            raise forms.ValidationError("This email is already in use.")
        return email


# forms.py
from django import forms
from django.contrib.auth import authenticate
from django.utils.translation import gettext_lazy as _


class CustomLoginForm(forms.Form):
    username = forms.CharField(
        label=_("Email or Username"),
        max_length=150,
        widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Email or Username'})
    )
    password = forms.CharField(
        label=_("Password"),
        widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Password'})
    )

    def clean(self):
        cleaned_data = super().clean()
        username = cleaned_data.get('username')
        password = cleaned_data.get('password')

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError(
                    _("Invalid email/username or password.")
                )
        return cleaned_data

blogs/views.py
from django.shortcuts import render

from blogs.models import BlogsModel


def home_page_view(request):
    return render(request, 'home.html')


def blogs_page_view(request):
    blogs = BlogsModel.objects.filter(author__is_active=True)

    context = {
        "blogs": blogs
    }

    return render(request, 'blogs.html', context)


def contact_page_view(request):
    return render(request, 'contacts.html')

users/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.tokens import default_token_generator
from django.http import HttpResponse
from django.shortcuts import render, redirect

from .forms import CustomUserCreationForm, CustomLoginForm
from .models import CustomUserModel
from .utils import send_email_confirmation


def register_view(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False  # Deactivate account until email is confirmed
            user.save()
            send_email_confirmation(user, request)
            messages.success(request, "A confirmation email has been sent to your email address.")
            return redirect('users:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'register.html', {'form': form})


def email_confirm_view(request, uid, token):
    try:
        user = CustomUserModel.objects.get(pk=uid)
    except CustomUserModel.DoesNotExist:
        return HttpResponse("Invalid confirmation link.", status=400)

    if default_token_generator.check_token(user, token):
        user.is_active = True  # Activate the user
        user.save()
        return redirect('users:login')
    else:
        return HttpResponse("Invalid or expired token.", status=400)


def login_view(request):
    if request.method == 'POST':
        form = CustomLoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                login(request, user)
                messages.success(request, "You have successfully logged in.")
                return redirect('/')  # Replace 'home' with your desired URL name
            else:
                form.add_error(None, "Invalid email/username or password.")
    else:
        form = CustomLoginForm()
    return render(request, 'login.html', {'form': form})

blogs/templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<h1>Hello world !</h1>
</body>
</html>

templates/blogs.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>

{% include 'navbar.html' %}

<div class="container">
    <div class="row row-cols-1 row-cols-md-3 g-4 mt-4">
        {% for blog in blogs %}
            <div class="col">
                <div class="card h-100">
                    <img src="{{ blog.image.url }}"
                         class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ blog.title }}</h5>
                        <p class="card-text">{{ blog.content }}</p>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <nav aria-label="Page navigation example" class="mt-5">
        <ul class="pagination justify-content-center">
            <li class="page-item disabled">
                <a class="page-link">Previous</a>
            </li>
            <li class="page-item"><a class="page-link" href="#">1</a></li>
            <li class="page-item"><a class="page-link" href="#">2</a></li>
            <li class="page-item"><a class="page-link" href="#">3</a></li>
            <li class="page-item">
                <a class="page-link" href="#">Next</a>
            </li>
        </ul>
    </nav>
</div>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/contacts.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>

{% include 'navbar.html' %}

{# bir ba #}


<div class="container">
<h1>Contact page</h1>
</div>

{# blogs #}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/email_confirmation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>Hi {{ user.username }},</p>
<p>Thank you for registering. Please click the link below to confirm your email address:</p>
<p><a href="{{ confirmation_link }}">Confirm Email</a></p>
<p>If you did not sign up for this account, you can safely ignore this email.</p>

</body>
</html>

templates/home.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css">
</head>
<body>
{% include 'navbar.html' %}

{# bir ba #}


<div class="container">
    <div id="carouselExampleIndicators" class="carousel slide">
        <div class="carousel-indicators">
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active"
                    aria-current="true" aria-label="Slide 1"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1"
                    aria-label="Slide 2"></button>
            <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2"
                    aria-label="Slide 3"></button>
        </div>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4rBLSSi2ajTwpfteImu34jT2my0PCHyyLMA&s"
                     class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4rBLSSi2ajTwpfteImu34jT2my0PCHyyLMA&s"
                     class="d-block w-100" alt="...">
            </div>
            <div class="carousel-item">
                <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT4rBLSSi2ajTwpfteImu34jT2my0PCHyyLMA&s"
                     class="d-block w-100" alt="...">
            </div>
        </div>
        <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
        </button>
        <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators"
                data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
        </button>
    </div>
</div>

{# blogs #}


<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h2>Login</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Login</button>
    </form>
    <p>Don't have an account? <a href="{% url 'users:login' %}">Register here</a></p>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary mb-4">
    <div class="container">
        <div class="container-fluid">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'blogs:home' %}">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'blogs:list' %}">Blogs</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'blogs:contact' %}">Contacts</a>
                    </li>

                </ul>
                <form class="d-flex" role="search">
                    <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success" type="submit">Search</button>
                </form>
            </div>
        </div>
    </div>
w

</nav>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Register</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
</head>
<body>
    <div class="container mt-5">
        <h2>Register</h2>
        <form method="post">
            {% csrf_token %}
            <div class="mb-3">
                {{ form.username.label_tag }}
                {{ form.username }}
                {% for error in form.username.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.email.label_tag }}
                {{ form.email }}
                {% for error in form.email.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.password1.label_tag }}
                {{ form.password1 }}
                {% for error in form.password1.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            <div class="mb-3">
                {{ form.password2.label_tag }}
                {{ form.password2 }}
                {% for error in form.password2.errors %}
                    <div class="text-danger">{{ error }}</div>
                {% endfor %}
            </div>
            <button type="submit" class="btn btn-primary">Register</button>
        </form>
        <p class="mt-3">Already have an account? <a href="{% url 'users:login' %}">Login here</a></p>
    </div>
</body>
</html>

templates/test_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="/" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form }}
    <button type="submit">Send</button>
</form>
</body>
</html>